# Generated by Django 4.0.1 on 2022-01-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='month.month')),
            ],
        ),
    ]
