# Generated by Django 4.0.1 on 2022-01-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.IntegerField(default=1),
        ),
    ]
