# Generated by Django 4.0.1 on 2022-01-22 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_dates_affected'),
        ('day', '0003_remove_day_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
