# Generated by Django 4.0.1 on 2022-01-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0004_day_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='event',
        ),
    ]
