# Generated by Django 4.0.1 on 2022-01-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_remove_day_week'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dates_affected',
            field=models.ManyToManyField(to='day.Day'),
        ),
    ]
