# Generated by Django 4.0.1 on 2022-01-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dates_affected',
        ),
    ]
