# Generated by Django 4.0.1 on 2022-01-22 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0002_alter_month_amountofdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='starting_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
